server:
  port: 7090
  servlet:
    context-path: /api
    session:
      timeout: PT60M

spring:
  mvc:
    favicon:
      enable: false
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 2463525846
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #  smtp.qq.com
  mail:
    port: 465
    username: 2463525846@qq.com
    password: wliledutkgqeeacc
    default-encoding: UTF-8
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
      debug: true
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000

project:
  folder: D:/desktop/date/easypandate

log:
  root:
    level: info
admin:
  emails: 2463525846@qq.com

dev: false
qq:
  app:
    id: 12333
    key: 2222222
  url:
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    access:
      token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    user:
      info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
      redirect: http://easypan.wuhancoder.com/qqlogincalback
mybatis-plus:
  type-aliases-package: com.easypan.pojo
  configuration:
    map-underscore-to-camel-case: true
